#ifndef GL_FUNCTIONS_hh
#define GL_FUNCTIONS_hh

#define GL_GLEXT_PROTOTYPES
#include <GL/gl.h>
#include <GL/glext.h>

#define FOR_GL_FUNCTIONS(X)\
    X(glGetError, getError)\
    X(glBlendFunc, blendFunc)\
    X(glCullFace, cullFace)\
    X(glEnable, enable)\
    X(glFrontFace, frontFace)\
    X(glAttachShader, attachShader)\
    X(glCompileShader, compileShader)\
    X(glCreateShader, createShader)\
    X(glDeleteShader, deleteShader)\
    X(glGetShaderInfoLog, getShaderInfoLog)\
    X(glGetShaderiv, getShaderiv)\
    X(glShaderSource, shaderSource)\
    X(glCreateProgram, createProgram)\
    X(glDeleteProgram, deleteProgram)\
    X(glGetProgramInfoLog, getProgramInfoLog)\
    X(glGetProgramiv, getProgramiv)\
    X(glLinkProgram, linkProgram)\
    X(glUseProgram, useProgram)\
    X(glClear, clear)\
    X(glClearColor, clearColor)\
    X(glBindVertexArray, bindVertexArray)\
    X(glDeleteVertexArrays, deleteVertexArrays)\
    X(glGenVertexArrays, genVertexArrays)\
    X(glBindBuffer, bindBuffer)\
    X(glBufferData, bufferData)\
    X(glDeleteBuffers, deleteBuffers)\
    X(glGenBuffers, genBuffers)\
    X(glActiveTexture, activeTexture)\
    X(glBindTexture, bindTexture)\
    X(glDeleteTextures, deleteTextures)\
    X(glGenTextures, genTextures)\
    X(glTexImage2D, texImage2D)\
    X(glTexParameteri, texParameteri)\
    X(glTexStorage2D, texStorage2D)\
    X(glEnableVertexAttribArray, enableVertexAttribArray)\
    X(glGetAttribLocation, getAttribLocation)\
    X(glVertexAttribDivisor, vertexAttribDivisor)\
    X(glVertexAttribPointer, vertexAttribPointer)\
    X(glGetUniformLocation, getUniformLocation)\
    X(glUniform1f, uniform1f)\
    X(glUniform1i, uniform1i)\
    X(glUniform3fv, uniform3fv)\
    X(glUniformMatrix4fv, uniformMatrix4fv)\
    X(glDrawArrays, drawArrays)\
    X(glDrawArraysInstanced, drawArraysInstanced)

#endif // GL_FUNCTIONS_hh
